# Generated by Django 2.2.4 on 2019-08-06 09:11

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('accounts', '0002_notification_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOfPeople',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('parent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='accounts.GroupOfPeople', verbose_name='Parent group')),
            ],
            options={
                'verbose_name': 'group of people',
                'verbose_name_plural': 'groups of people',
                'ordering': ('name',),
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
