# Generated by Django 3.0.5 on 2020-04-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200404_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='firstLogin',
            field=models.BooleanField(default=True),
        ),
    ]
