# Generated by Django 3.0.5 on 2020-04-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_person_firstlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('color', models.CharField(default='#007bff', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='interests',
            field=models.ManyToManyField(related_name='student_prefernces', to='accounts.Preferences'),
        ),
    ]
