# Generated by Django 3.0.5 on 2020-04-10 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200410_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='interests',
            new_name='preferences',
        ),
    ]
