# Generated by Django 2.2.10 on 2020-03-07 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import learning.permissions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0003_object_collaborators'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionMixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Question body')),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Published the')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last updated the')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            bases=(learning.permissions.ObjectPermissionManagerMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-updated', 'name'], 'verbose_name': 'activity', 'verbose_name_plural': 'activities'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-updated', 'name'], 'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-updated', 'name'], 'verbose_name': 'resource', 'verbose_name_plural': 'resources'},
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Response body')),
                ('score', models.IntegerField(default=0, verbose_name='Score Count')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Response publication date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last updated the')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='learning.QuestionMixin', verbose_name='Question')),
                ('voters', models.ManyToManyField(related_name='responses_votes', to=settings.AUTH_USER_MODEL, verbose_name='Users that voted for the response')),
            ],
            options={
                'verbose_name': 'response',
                'verbose_name_plural': 'responses',
                'ordering': ['question', 'created'],
            },
            bases=(learning.permissions.ObjectPermissionManagerMixin, models.Model),
        ),
        migrations.CreateModel(
            name='QuestionCourse',
            fields=[
                ('questionmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='learning.QuestionMixin')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.Course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'course question',
                'verbose_name_plural': 'course questions',
                'ordering': ['course', 'created'],
            },
            bases=('learning.questionmixin',),
        ),
    ]
